name = "vybe-workshop"
compatibility_date = "2024-12-20"
pages_build_output_dir = "."

[durable_objects]
bindings = [{ name = "CHAT_ROOM", class_name = "ChatRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
